services:
  worker:
#    container_name: worker
    build:
      context: .
      dockerfile: ./docker/worker/Dockerfile
    tty: true
    command: bash -c "rq worker high default low --config rq_conf"
    deploy:
      replicas: 10
#      resources:
#        limits:
#          cpus: '0.25'
#          memory: '50M'
#        reservations:
#          cpus: '0.25'
#          memory: '50M'
    volumes:
      - ./src:/src
#    networks:
#      - worker

  rq_redis:
    image: redis:6.2.7
    ports:
      - "6379:6379"
    container_name: rq_redis
    restart: always
    environment:
      - TZ=Europe/Moscow
#    networks:
#      - worker
#      - default

#networks:
#  worker: