REDIS_HOST = "rq_redis"
# REDIS_PORT = port
# REDIS_PASSWORD = "password"
# REDIS_SSL = True
# REDIS_SSL_CA_CERTS = None
REDIS_DB = 0
# REDIS_SSL_CERT_REQS = None
# REDIS_SSL_CA_DATA = "-----BEGIN CERTIFICATE-----\n****"
